# Generated by Django 5.0.2 on 2024-02-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_product_lesson_lesson_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='student',
        ),
    ]
